// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ddloglik
List ddloglik(int n, arma::colvec delta, arma::mat z, arma::colvec beta, arma::mat offset);
RcppExport SEXP _CoxAdditive_ddloglik(SEXP nSEXP, SEXP deltaSEXP, SEXP zSEXP, SEXP betaSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik(n, delta, z, beta, offset));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CoxAdditive_ddloglik", (DL_FUNC) &_CoxAdditive_ddloglik, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_CoxAdditive(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
